# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    # début code ajouté
    def __init__(self, controleur):
        self.controleur = controleur
    # fin code ajouté

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 608)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabs.setFont(font)
        self.tabs.setAutoFillBackground(True)
        self.tabs.setElideMode(QtCore.Qt.ElideNone)
        self.tabs.setDocumentMode(True)
        self.tabs.setTabsClosable(False)
        self.tabs.setMovable(False)
        self.tabs.setTabBarAutoHide(False)
        self.tabs.setObjectName("tabs")
        self.positionTab = QtWidgets.QWidget()
        self.positionTab.setAutoFillBackground(True)
        self.positionTab.setObjectName("positionTab")
        self.gridLayout = QtWidgets.QGridLayout(self.positionTab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.positionTab)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 8, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.positionTab)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 9, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.positionTab)
        self.line_3.setAutoFillBackground(True)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setLineWidth(0)
        self.line_3.setMidLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 7, 0, 1, 11)
        self.lineEditFreq_p = QtWidgets.QLineEdit(self.positionTab)
        self.lineEditFreq_p.setText("")
        self.lineEditFreq_p.setObjectName("lineEditFreq_p")
        self.gridLayout.addWidget(self.lineEditFreq_p, 6, 10, 1, 1)
        self.radioButtonRam_p = QtWidgets.QRadioButton(self.positionTab)
        self.radioButtonRam_p.setObjectName("radioButtonRam_p")
        self.buttonGroup_p = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_p.setObjectName("buttonGroup_p")
        self.buttonGroup_p.addButton(self.radioButtonRam_p)
        self.gridLayout.addWidget(self.radioButtonRam_p, 5, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.positionTab)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.positionTab)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 2, 1, 1)
        self.lineEditCoefDir_p = QtWidgets.QLineEdit(self.positionTab)
        self.lineEditCoefDir_p.setText("")
        self.lineEditCoefDir_p.setObjectName("lineEditCoefDir_p")
        self.gridLayout.addWidget(self.lineEditCoefDir_p, 5, 10, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.positionTab)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 8, 9, 1, 1)
        self.lineEditDur_p = QtWidgets.QLineEdit(self.positionTab)
        self.lineEditDur_p.setText("")
        self.lineEditDur_p.setObjectName("lineEditDur_p")
        self.gridLayout.addWidget(self.lineEditDur_p, 8, 7, 1, 1)
        self.line = QtWidgets.QFrame(self.positionTab)
        self.line.setAutoFillBackground(True)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 11)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 10, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 7, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.positionTab)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 7, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 6, 7, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.positionTab)
        self.line_2.setAutoFillBackground(True)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setLineWidth(0)
        self.line_2.setMidLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 11)
        self.run_p = QtWidgets.QPushButton(self.positionTab)
        self.run_p.setObjectName("run_p")
        self.gridLayout.addWidget(self.run_p, 9, 7, 1, 1)
        self.lineEditPosFEch_p = QtWidgets.QLineEdit(self.positionTab)
        self.lineEditPosFEch_p.setText("")
        self.lineEditPosFEch_p.setObjectName("lineEditPosFEch_p")
        self.gridLayout.addWidget(self.lineEditPosFEch_p, 4, 3, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.positionTab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 8, 1, 1)
        self.label = QtWidgets.QLabel(self.positionTab)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 5, 1, 1)
        self.poLabelValeurPosAct_p = QtWidgets.QLabel(self.positionTab)
        self.poLabelValeurPosAct_p.setObjectName("poLabelValeurPosAct_p")
        self.gridLayout.addWidget(self.poLabelValeurPosAct_p, 0, 7, 1, 1)
        self.lineEditPosFRam_p = QtWidgets.QLineEdit(self.positionTab)
        self.lineEditPosFRam_p.setText("")
        self.lineEditPosFRam_p.setObjectName("lineEditPosFRam_p")
        self.gridLayout.addWidget(self.lineEditPosFRam_p, 5, 3, 1, 4)
        self.lineEditAmp_p = QtWidgets.QLineEdit(self.positionTab)
        self.lineEditAmp_p.setText("")
        self.lineEditAmp_p.setObjectName("lineEditAmp_p")
        self.gridLayout.addWidget(self.lineEditAmp_p, 6, 3, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.positionTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 2, 1, 1)
        self.radioButtonEch_p = QtWidgets.QRadioButton(self.positionTab)
        self.radioButtonEch_p.setChecked(True)
        self.radioButtonEch_p.setObjectName("radioButtonEch_p")
        self.buttonGroup_p.addButton(self.radioButtonEch_p)
        self.gridLayout.addWidget(self.radioButtonEch_p, 4, 0, 1, 2)
        self.radioButtonSin_p = QtWidgets.QRadioButton(self.positionTab)
        self.radioButtonSin_p.setObjectName("radioButtonSin_p")
        self.buttonGroup_p.addButton(self.radioButtonSin_p)
        self.gridLayout.addWidget(self.radioButtonSin_p, 6, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.positionTab)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 3, 1, 3)
        self.tabs.addTab(self.positionTab, "")
        self.vitesseTab = QtWidgets.QWidget()
        self.vitesseTab.setAutoFillBackground(True)
        self.vitesseTab.setObjectName("vitesseTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.vitesseTab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtWidgets.QLabel(self.vitesseTab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.vitesseTab)
        self.line_4.setAutoFillBackground(True)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setLineWidth(0)
        self.line_4.setMidLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 3, 0, 1, 9)
        self.label_12 = QtWidgets.QLabel(self.vitesseTab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 6, 1, 1)
        self.radioButtonEch_v = QtWidgets.QRadioButton(self.vitesseTab)
        self.radioButtonEch_v.setChecked(True)
        self.radioButtonEch_v.setObjectName("radioButtonEch_v")
        self.buttonGroup_v = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_v.setObjectName("buttonGroup_v")
        self.buttonGroup_v.addButton(self.radioButtonEch_v)
        self.gridLayout_4.addWidget(self.radioButtonEch_v, 4, 0, 1, 1)
        self.lineEditPosFEch_v = QtWidgets.QLineEdit(self.vitesseTab)
        self.lineEditPosFEch_v.setText("")
        self.lineEditPosFEch_v.setObjectName("lineEditPosFEch_v")
        self.gridLayout_4.addWidget(self.lineEditPosFEch_v, 4, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.vitesseTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.vitesseTab)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 5, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.vitesseTab)
        self.line_6.setAutoFillBackground(True)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setLineWidth(0)
        self.line_6.setMidLineWidth(3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.gridLayout_4.addWidget(self.line_6, 1, 0, 1, 9)
        self.label_9 = QtWidgets.QLabel(self.vitesseTab)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 6, 7, 1, 1)
        self.lineEditPosFTri_v = QtWidgets.QLineEdit(self.vitesseTab)
        self.lineEditPosFTri_v.setText("")
        self.lineEditPosFTri_v.setObjectName("lineEditPosFTri_v")
        self.gridLayout_4.addWidget(self.lineEditPosFTri_v, 5, 2, 1, 1)
        self.lineEditCoefDir_v = QtWidgets.QLineEdit(self.vitesseTab)
        self.lineEditCoefDir_v.setText("")
        self.lineEditCoefDir_v.setObjectName("lineEditCoefDir_v")
        self.gridLayout_4.addWidget(self.lineEditCoefDir_v, 5, 8, 1, 1)
        self.radioButtonTri_v = QtWidgets.QRadioButton(self.vitesseTab)
        self.radioButtonTri_v.setObjectName("radioButtonTri_v")
        self.buttonGroup_v.addButton(self.radioButtonTri_v)
        self.gridLayout_4.addWidget(self.radioButtonTri_v, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.vitesseTab)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 6, 1, 1, 1)
        self.lineEditFreq_v = QtWidgets.QLineEdit(self.vitesseTab)
        self.lineEditFreq_v.setText("")
        self.lineEditFreq_v.setObjectName("lineEditFreq_v")
        self.gridLayout_4.addWidget(self.lineEditFreq_v, 6, 8, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem4, 8, 8, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.vitesseTab)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 8, 7, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.vitesseTab)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 8, 2, 1, 1)
        self.lineEditAmp_v = QtWidgets.QLineEdit(self.vitesseTab)
        self.lineEditAmp_v.setText("")
        self.lineEditAmp_v.setObjectName("lineEditAmp_v")
        self.gridLayout_4.addWidget(self.lineEditAmp_v, 6, 2, 1, 1)
        self.radioButtonSin_v = QtWidgets.QRadioButton(self.vitesseTab)
        self.radioButtonSin_v.setObjectName("radioButtonSin_v")
        self.buttonGroup_v.addButton(self.radioButtonSin_v)
        self.gridLayout_4.addWidget(self.radioButtonSin_v, 6, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.vitesseTab)
        self.line_5.setAutoFillBackground(True)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setLineWidth(0)
        self.line_5.setMidLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout_4.addWidget(self.line_5, 7, 0, 1, 9)
        spacerItem5 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 5, 5, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.vitesseTab)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 5, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 6, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem7, 4, 5, 1, 1)
        self.lineEditPlat_v = QtWidgets.QLineEdit(self.vitesseTab)
        self.lineEditPlat_v.setObjectName("lineEditPlat_v")
        self.gridLayout_4.addWidget(self.lineEditPlat_v, 5, 4, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.vitesseTab)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 2, 3, 1, 3)
        self.poLabelValeurPosAct_v = QtWidgets.QLabel(self.vitesseTab)
        self.poLabelValeurPosAct_v.setObjectName("poLabelValeurPosAct_v")
        self.gridLayout_4.addWidget(self.poLabelValeurPosAct_v, 0, 3, 1, 3)
        self.lineEditDur_v = QtWidgets.QLineEdit(self.vitesseTab)
        self.lineEditDur_v.setText("")
        self.lineEditDur_v.setObjectName("lineEditDur_v")
        self.gridLayout_4.addWidget(self.lineEditDur_v, 8, 3, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.vitesseTab)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 5, 6, 1, 2)
        self.run_v = QtWidgets.QPushButton(self.vitesseTab)
        self.run_v.setObjectName("run_v")
        self.gridLayout_4.addWidget(self.run_v, 9, 3, 1, 3)
        self.tabs.addTab(self.vitesseTab, "")
        self.courantTab = QtWidgets.QWidget()
        self.courantTab.setAutoFillBackground(True)
        self.courantTab.setObjectName("courantTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.courantTab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.poLabelValeurPosAct_c = QtWidgets.QLabel(self.courantTab)
        self.poLabelValeurPosAct_c.setObjectName("poLabelValeurPosAct_c")
        self.gridLayout_3.addWidget(self.poLabelValeurPosAct_c, 0, 3, 1, 3)
        self.lineEditDur_c = QtWidgets.QLineEdit(self.courantTab)
        self.lineEditDur_c.setText("")
        self.lineEditDur_c.setObjectName("lineEditDur_c")
        self.gridLayout_3.addWidget(self.lineEditDur_c, 8, 3, 1, 3)
        self.label_30 = QtWidgets.QLabel(self.courantTab)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 2, 3, 1, 3)
        self.run_c = QtWidgets.QPushButton(self.courantTab)
        self.run_c.setObjectName("run_c")
        self.gridLayout_3.addWidget(self.run_c, 9, 3, 1, 3)
        self.label_26 = QtWidgets.QLabel(self.courantTab)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.courantTab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 8, 7, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem8, 8, 8, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.courantTab)
        self.line_8.setAutoFillBackground(True)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setLineWidth(0)
        self.line_8.setMidLineWidth(3)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout_3.addWidget(self.line_8, 7, 0, 1, 9)
        self.label_29 = QtWidgets.QLabel(self.courantTab)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 8, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.courantTab)
        self.line_7.setAutoFillBackground(True)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setLineWidth(0)
        self.line_7.setMidLineWidth(3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.gridLayout_3.addWidget(self.line_7, 3, 0, 1, 9)
        self.label_24 = QtWidgets.QLabel(self.courantTab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 0, 6, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.courantTab)
        self.line_9.setAutoFillBackground(True)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setLineWidth(0)
        self.line_9.setMidLineWidth(3)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setObjectName("line_9")
        self.gridLayout_3.addWidget(self.line_9, 1, 0, 1, 9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 4, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.courantTab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 4, 1, 1, 1)
        self.lineEditPosFEch_c = QtWidgets.QLineEdit(self.courantTab)
        self.lineEditPosFEch_c.setText("")
        self.lineEditPosFEch_c.setObjectName("lineEditPosFEch_c")
        self.gridLayout_3.addWidget(self.lineEditPosFEch_c, 4, 2, 1, 1)
        self.radioButtonRam_c = QtWidgets.QRadioButton(self.courantTab)
        self.radioButtonRam_c.setObjectName("radioButtonRam_c")
        self.buttonGroup_c = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_c.setObjectName("buttonGroup_c")
        self.buttonGroup_c.addButton(self.radioButtonRam_c)
        self.gridLayout_3.addWidget(self.radioButtonRam_c, 5, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.courantTab)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 5, 1, 1, 1)
        self.radioButtonEch_c = QtWidgets.QRadioButton(self.courantTab)
        self.radioButtonEch_c.setChecked(True)
        self.radioButtonEch_c.setObjectName("radioButtonEch_c")
        self.buttonGroup_c.addButton(self.radioButtonEch_c)
        self.gridLayout_3.addWidget(self.radioButtonEch_c, 4, 0, 1, 1)
        self.lineEditCoefDir_c = QtWidgets.QLineEdit(self.courantTab)
        self.lineEditCoefDir_c.setText("")
        self.lineEditCoefDir_c.setObjectName("lineEditCoefDir_c")
        self.gridLayout_3.addWidget(self.lineEditCoefDir_c, 5, 8, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.courantTab)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 5, 6, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem10, 5, 5, 1, 1)
        self.lineEditPosFRam_c = QtWidgets.QLineEdit(self.courantTab)
        self.lineEditPosFRam_c.setText("")
        self.lineEditPosFRam_c.setObjectName("lineEditPosFRam_c")
        self.gridLayout_3.addWidget(self.lineEditPosFRam_c, 5, 2, 1, 1)
        self.radioButtonSin_c = QtWidgets.QRadioButton(self.courantTab)
        self.radioButtonSin_c.setObjectName("radioButtonSin_c")
        self.buttonGroup_c.addButton(self.radioButtonSin_c)
        self.gridLayout_3.addWidget(self.radioButtonSin_c, 6, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.courantTab)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 6, 7, 1, 1)
        self.lineEditFreq_c = QtWidgets.QLineEdit(self.courantTab)
        self.lineEditFreq_c.setText("")
        self.lineEditFreq_c.setObjectName("lineEditFreq_c")
        self.gridLayout_3.addWidget(self.lineEditFreq_c, 6, 8, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.courantTab)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 6, 1, 1, 1)
        self.lineEditAmp_c = QtWidgets.QLineEdit(self.courantTab)
        self.lineEditAmp_c.setText("")
        self.lineEditAmp_c.setObjectName("lineEditAmp_c")
        self.gridLayout_3.addWidget(self.lineEditAmp_c, 6, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 94, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 6, 5, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.courantTab)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 5, 3, 1, 1)
        self.lineEditPlat_c = QtWidgets.QLineEdit(self.courantTab)
        self.lineEditPlat_c.setObjectName("lineEditPlat_c")
        self.gridLayout_3.addWidget(self.lineEditPlat_c, 5, 4, 1, 1)
        self.tabs.addTab(self.courantTab, "")
        self.collaboTab = QtWidgets.QWidget()
        self.collaboTab.setAutoFillBackground(True)
        self.collaboTab.setObjectName("collaboTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.collaboTab)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem12, 1, 4, 1, 1)
        self.lineEditTd_col = QtWidgets.QLineEdit(self.collaboTab)
        self.lineEditTd_col.setObjectName("lineEditTd_col")
        self.gridLayout_5.addWidget(self.lineEditTd_col, 3, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.collaboTab)
        self.label_55.setObjectName("label_55")
        self.gridLayout_5.addWidget(self.label_55, 3, 1, 1, 1)
        self.lineEditTi_col = QtWidgets.QLineEdit(self.collaboTab)
        self.lineEditTi_col.setObjectName("lineEditTi_col")
        self.gridLayout_5.addWidget(self.lineEditTi_col, 2, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem13, 2, 4, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem14, 0, 4, 1, 1)
        self.run_col = QtWidgets.QPushButton(self.collaboTab)
        self.run_col.setObjectName("run_col")
        self.gridLayout_5.addWidget(self.run_col, 4, 2, 1, 1)
        self.poLabelValeurPosAct_col = QtWidgets.QLabel(self.collaboTab)
        self.poLabelValeurPosAct_col.setObjectName("poLabelValeurPosAct_col")
        self.gridLayout_5.addWidget(self.poLabelValeurPosAct_col, 2, 9, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem15, 3, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.collaboTab)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 2, 6, 1, 1)
        self.Slider_col = QtWidgets.QSlider(self.collaboTab)
        self.Slider_col.setOrientation(QtCore.Qt.Vertical)
        self.Slider_col.setObjectName("Slider_col")
        self.gridLayout_5.addWidget(self.Slider_col, 0, 8, 5, 1)
        self.lineEditK_col = QtWidgets.QLineEdit(self.collaboTab)
        self.lineEditK_col.setObjectName("lineEditK_col")
        self.gridLayout_5.addWidget(self.lineEditK_col, 1, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.collaboTab)
        self.label_39.setObjectName("label_39")
        self.gridLayout_5.addWidget(self.label_39, 1, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.collaboTab)
        self.label_40.setObjectName("label_40")
        self.gridLayout_5.addWidget(self.label_40, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.collaboTab)
        self.label_56.setObjectName("label_56")
        self.gridLayout_5.addWidget(self.label_56, 0, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem16, 2, 7, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem17, 2, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem18, 2, 5, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem19, 2, 10, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.collaboTab)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_5.addWidget(self.pushButton, 5, 2, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem20, 4, 4, 2, 1)
        self.tabs.addTab(self.collaboTab, "")
        self.correcteurTab = QtWidgets.QWidget()
        self.correcteurTab.setObjectName("correcteurTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.correcteurTab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEditTdPos_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditTdPos_cor.setObjectName("lineEditTdPos_cor")
        self.gridLayout_6.addWidget(self.lineEditTdPos_cor, 12, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.correcteurTab)
        self.label_44.setObjectName("label_44")
        self.gridLayout_6.addWidget(self.label_44, 9, 4, 1, 1)
        self.radioButtonCour_col = QtWidgets.QRadioButton(self.correcteurTab)
        self.radioButtonCour_col.setObjectName("radioButtonCour_col")
        self.buttonGroup_cor = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_cor.setObjectName("buttonGroup_cor")
        self.buttonGroup_cor.addButton(self.radioButtonCour_col)
        self.gridLayout_6.addWidget(self.radioButtonCour_col, 4, 0, 1, 2)
        self.lineEditKCour_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditKCour_cor.setObjectName("lineEditKCour_cor")
        self.gridLayout_6.addWidget(self.lineEditKCour_cor, 10, 7, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.correcteurTab)
        self.label_48.setObjectName("label_48")
        self.gridLayout_6.addWidget(self.label_48, 10, 3, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.correcteurTab)
        self.label_46.setObjectName("label_46")
        self.gridLayout_6.addWidget(self.label_46, 11, 0, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.correcteurTab)
        self.label_49.setObjectName("label_49")
        self.gridLayout_6.addWidget(self.label_49, 11, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.correcteurTab)
        self.label_45.setObjectName("label_45")
        self.gridLayout_6.addWidget(self.label_45, 10, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.correcteurTab)
        self.label_54.setObjectName("label_54")
        self.gridLayout_6.addWidget(self.label_54, 9, 7, 1, 1)
        self.radioButtonPos_cor = QtWidgets.QRadioButton(self.correcteurTab)
        self.radioButtonPos_cor.setChecked(True)
        self.radioButtonPos_cor.setObjectName("radioButtonPos_cor")
        self.buttonGroup_cor.addButton(self.radioButtonPos_cor)
        self.gridLayout_6.addWidget(self.radioButtonPos_cor, 2, 0, 1, 2)
        self.radioButton_13 = QtWidgets.QRadioButton(self.correcteurTab)
        self.radioButton_13.setObjectName("radioButton_13")
        self.buttonGroup_cor.addButton(self.radioButton_13)
        self.gridLayout_6.addWidget(self.radioButton_13, 3, 0, 1, 2)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem21, 2, 7, 2, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem22, 10, 8, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem23, 4, 7, 2, 1)
        self.lineEditKVit_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditKVit_cor.setObjectName("lineEditKVit_cor")
        self.gridLayout_6.addWidget(self.lineEditKVit_cor, 10, 4, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.correcteurTab)
        self.label_51.setObjectName("label_51")
        self.gridLayout_6.addWidget(self.label_51, 10, 6, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.correcteurTab)
        self.line_15.setLineWidth(0)
        self.line_15.setMidLineWidth(3)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout_6.addWidget(self.line_15, 8, 0, 1, 8)
        self.lineEditKPos_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditKPos_cor.setObjectName("lineEditKPos_cor")
        self.gridLayout_6.addWidget(self.lineEditKPos_cor, 10, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.correcteurTab)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 9, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.correcteurTab)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 7, 3, 1, 2)
        self.line_14 = QtWidgets.QFrame(self.correcteurTab)
        self.line_14.setLineWidth(0)
        self.line_14.setMidLineWidth(3)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout_6.addWidget(self.line_14, 6, 0, 1, 8)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem24, 11, 8, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.correcteurTab)
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 11, 6, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.correcteurTab)
        self.label_47.setObjectName("label_47")
        self.gridLayout_6.addWidget(self.label_47, 12, 0, 1, 1)
        self.lineEditTdVit_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditTdVit_cor.setObjectName("lineEditTdVit_cor")
        self.gridLayout_6.addWidget(self.lineEditTdVit_cor, 12, 4, 1, 1)
        self.lineEditTiVit_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditTiVit_cor.setObjectName("lineEditTiVit_cor")
        self.gridLayout_6.addWidget(self.lineEditTiVit_cor, 11, 4, 1, 1)
        self.lineEditTiPos_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditTiPos_cor.setObjectName("lineEditTiPos_cor")
        self.gridLayout_6.addWidget(self.lineEditTiPos_cor, 11, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.correcteurTab)
        self.label_50.setObjectName("label_50")
        self.gridLayout_6.addWidget(self.label_50, 12, 3, 1, 1)
        self.radioButtonCas_col = QtWidgets.QRadioButton(self.correcteurTab)
        self.radioButtonCas_col.setObjectName("radioButtonCas_col")
        self.buttonGroup_cor.addButton(self.radioButtonCas_col)
        self.gridLayout_6.addWidget(self.radioButtonCas_col, 5, 0, 1, 2)
        self.lineEditTdCour_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditTdCour_cor.setObjectName("lineEditTdCour_cor")
        self.gridLayout_6.addWidget(self.lineEditTdCour_cor, 12, 7, 1, 1)
        self.lineEditTiCour_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditTiCour_cor.setObjectName("lineEditTiCour_cor")
        self.gridLayout_6.addWidget(self.lineEditTiCour_cor, 11, 7, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.correcteurTab)
        self.label_52.setObjectName("label_52")
        self.gridLayout_6.addWidget(self.label_52, 12, 6, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.correcteurTab)
        self.line_13.setLineWidth(0)
        self.line_13.setMidLineWidth(3)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_6.addWidget(self.line_13, 1, 0, 1, 8)
        self.label_41 = QtWidgets.QLabel(self.correcteurTab)
        self.label_41.setObjectName("label_41")
        self.gridLayout_6.addWidget(self.label_41, 0, 3, 1, 2)
        self.line_16 = QtWidgets.QFrame(self.correcteurTab)
        self.line_16.setLineWidth(2)
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout_6.addWidget(self.line_16, 10, 2, 4, 1)
        self.line_17 = QtWidgets.QFrame(self.correcteurTab)
        self.line_17.setLineWidth(2)
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout_6.addWidget(self.line_17, 10, 5, 4, 1)
        self.label_35 = QtWidgets.QLabel(self.correcteurTab)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 13, 0, 1, 1)
        self.lineEditSatVit_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditSatVit_cor.setObjectName("lineEditSatVit_cor")
        self.gridLayout_6.addWidget(self.lineEditSatVit_cor, 13, 4, 1, 1)
        self.lineEditSatCour_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditSatCour_cor.setObjectName("lineEditSatCour_cor")
        self.gridLayout_6.addWidget(self.lineEditSatCour_cor, 13, 7, 1, 1)
        self.lineEditSatPos_cor = QtWidgets.QLineEdit(self.correcteurTab)
        self.lineEditSatPos_cor.setObjectName("lineEditSatPos_cor")
        self.gridLayout_6.addWidget(self.lineEditSatPos_cor, 13, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.correcteurTab)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 13, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.correcteurTab)
        self.label_37.setObjectName("label_37")
        self.gridLayout_6.addWidget(self.label_37, 13, 6, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem25, 12, 8, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem26, 13, 8, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.correcteurTab)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 2, 3, 3, 4)
        self.label_38 = QtWidgets.QLabel(self.correcteurTab)
        self.label_38.setObjectName("label_38")
        self.gridLayout_6.addWidget(self.label_38, 14, 0, 1, 8)
        self.tabs.addTab(self.correcteurTab, "")
        self.gridLayout_2.addWidget(self.tabs, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 875, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuAffichage = QtWidgets.QMenu(self.menubar)
        self.menuAffichage.setObjectName("menuAffichage")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuAffichage.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # début code ajouté
        self.run_col.clicked.connect(self.runcolabo)
        self.pushButton.clicked.connect(self.stopcolabo)
        self.run_p.clicked.connect(self.runpos)
        self.Slider_col.setMinimum(0)
        self.Slider_col.setMaximum(500)
        self.Slider_col.setDisabled(True)
        self.lineEditPosFEch_p.setText('0')
        self.lineEditPosFRam_p.setText('0')
        self.lineEditCoefDir_p.setText('0')
        self.lineEditAmp_p.setText('0')
        self.lineEditFreq_p.setText('0')
        self.lineEditDur_p.setText('0')
        self.lineEditPosFEch_v.setText('0')
        self.lineEditPosFTri_v.setText('0')
        self.lineEditPlat_v.setText('0')
        self.lineEditCoefDir_v.setText('0')
        self.lineEditAmp_v.setText('0')
        self.lineEditFreq_v.setText('0')
        self.lineEditDur_v.setText('0')
        self.lineEditPosFEch_c.setText('0')
        self.lineEditPosFRam_c.setText('0')
        self.lineEditPlat_c.setText('0')
        self.lineEditCoefDir_c.setText('0')
        self.lineEditAmp_c.setText('0')
        self.lineEditFreq_c.setText('0')
        self.lineEditDur_c.setText('0')
        self.lineEditKPos_cor.setText('1')
        self.lineEditTiPos_cor.setText('0')
        self.lineEditTdPos_cor.setText('0')
        self.lineEditSatPos_cor.setText('0')
        self.lineEditKVit_cor.setText('1')
        self.lineEditTiVit_cor.setText('0')
        self.lineEditTdVit_cor.setText('0')
        self.lineEditSatVit_cor.setText('0')
        self.lineEditKCour_cor.setText('1')
        self.lineEditTiCour_cor.setText('0')
        self.lineEditTdCour_cor.setText('0')
        self.lineEditSatCour_cor.setText('0')
        self.lineEditK_col.setText('1')
        self.lineEditTi_col.setText('0')
        self.lineEditTd_col.setText('0')
        # fin code ajouté

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "coefficient directeur"))
        self.label_7.setText(_translate("MainWindow", "fréquence"))
        self.radioButtonRam_p.setText(_translate("MainWindow", "Rampe"))
        self.label_6.setText(_translate("MainWindow", "amplitude"))
        self.label_5.setText(_translate("MainWindow", "position finale"))
        self.label_14.setText(_translate("MainWindow", "secondes"))
        self.label_2.setText(_translate("MainWindow", "Choix du profil de commande"))
        self.run_p.setText(_translate("MainWindow", "run"))
        self.label_3.setText(_translate("MainWindow", "cm"))
        self.label.setText(_translate("MainWindow", "position actuelle"))
        self.poLabelValeurPosAct_p.setText(_translate("MainWindow", "poLabelValeurPosAct"))
        self.label_4.setText(_translate("MainWindow", "position finale"))
        self.radioButtonEch_p.setText(_translate("MainWindow", "Echelon"))
        self.radioButtonSin_p.setText(_translate("MainWindow", "Sinus Asin(2pi*f*t)"))
        self.label_13.setText(_translate("MainWindow", "Durée expérimentale"))
        self.tabs.setTabText(self.tabs.indexOf(self.positionTab), _translate("MainWindow", "Position"))
        self.label_16.setText(_translate("MainWindow", "position actuelle"))
        self.label_12.setText(_translate("MainWindow", "cm"))
        self.radioButtonEch_v.setText(_translate("MainWindow", "Echelon"))
        self.label_18.setText(_translate("MainWindow", "position finale"))
        self.label_11.setText(_translate("MainWindow", "position finale"))
        self.label_9.setText(_translate("MainWindow", "fréquence"))
        self.radioButtonTri_v.setText(_translate("MainWindow", "trapèze"))
        self.label_15.setText(_translate("MainWindow", "amplitude"))
        self.label_17.setText(_translate("MainWindow", "secondes"))
        self.label_19.setText(_translate("MainWindow", "Durée expérimentale"))
        self.radioButtonSin_v.setText(_translate("MainWindow", "Sinus Asin(2pi*f*t)"))
        self.label_32.setText(_translate("MainWindow", "plateau"))
        self.label_20.setText(_translate("MainWindow", "Choix du profil de commande"))
        self.poLabelValeurPosAct_v.setText(_translate("MainWindow", "poLabelValeurPosAct"))
        self.label_10.setText(_translate("MainWindow", "coefficient directeur"))
        self.run_v.setText(_translate("MainWindow", "run"))
        self.tabs.setTabText(self.tabs.indexOf(self.vitesseTab), _translate("MainWindow", "Vitesse"))
        self.poLabelValeurPosAct_c.setText(_translate("MainWindow", "poLabelValeurPosAct"))
        self.label_30.setText(_translate("MainWindow", "Choix du profil de commande"))
        self.run_c.setText(_translate("MainWindow", "run"))
        self.label_26.setText(_translate("MainWindow", "position actuelle"))
        self.label_27.setText(_translate("MainWindow", "secondes"))
        self.label_29.setText(_translate("MainWindow", "Durée expérimentale"))
        self.label_24.setText(_translate("MainWindow", "cm"))
        self.label_28.setText(_translate("MainWindow", "position finale"))
        self.radioButtonRam_c.setText(_translate("MainWindow", "trapèze"))
        self.label_23.setText(_translate("MainWindow", "position finale"))
        self.radioButtonEch_c.setText(_translate("MainWindow", "Echelon"))
        self.label_22.setText(_translate("MainWindow", "coefficient directeur"))
        self.radioButtonSin_c.setText(_translate("MainWindow", "Sinus Asin(2pi*f*t)"))
        self.label_21.setText(_translate("MainWindow", "fréquence"))
        self.label_25.setText(_translate("MainWindow", "amplitude"))
        self.label_33.setText(_translate("MainWindow", "plateau"))
        self.tabs.setTabText(self.tabs.indexOf(self.courantTab), _translate("MainWindow", "Courant"))
        self.label_55.setText(_translate("MainWindow", "Td"))
        self.run_col.setText(_translate("MainWindow", "Run"))
        self.poLabelValeurPosAct_col.setText(_translate("MainWindow", "poLabelValeurPosAct"))
        self.label_31.setText(_translate("MainWindow", "Position du bras"))
        self.label_39.setText(_translate("MainWindow", "K"))
        self.label_40.setText(_translate("MainWindow", "Ti"))
        self.label_56.setText(_translate("MainWindow", "Correcteur d\'effort"))
        self.pushButton.setText(_translate("MainWindow", "stop"))
        self.tabs.setTabText(self.tabs.indexOf(self.collaboTab), _translate("MainWindow", "Collaboratif"))
        self.label_44.setText(_translate("MainWindow", "Vitesse"))
        self.radioButtonCour_col.setText(_translate("MainWindow", "regulation en courant"))
        self.label_48.setText(_translate("MainWindow", "K"))
        self.label_46.setText(_translate("MainWindow", "Ti"))
        self.label_49.setText(_translate("MainWindow", "Ti"))
        self.label_45.setText(_translate("MainWindow", "K"))
        self.label_54.setText(_translate("MainWindow", "Courant"))
        self.radioButtonPos_cor.setText(_translate("MainWindow", "regulation en position"))
        self.radioButton_13.setText(_translate("MainWindow", "regulation en vitesse"))
        self.label_51.setText(_translate("MainWindow", "K"))
        self.label_43.setText(_translate("MainWindow", "Position"))
        self.label_42.setText(_translate("MainWindow", "Choix des parametres des correcteurs"))
        self.label_53.setText(_translate("MainWindow", "Ti"))
        self.label_47.setText(_translate("MainWindow", "Td"))
        self.label_50.setText(_translate("MainWindow", "Td"))
        self.radioButtonCas_col.setText(_translate("MainWindow", "regulation cascade"))
        self.label_52.setText(_translate("MainWindow", "Td"))
        self.label_41.setText(_translate("MainWindow", "Choix du mode de correction"))
        self.label_35.setText(_translate("MainWindow", "Saturation"))
        self.label_36.setText(_translate("MainWindow", "Saturation"))
        self.label_37.setText(_translate("MainWindow", "Saturation"))
        self.label_34.setText(_translate("MainWindow", "K(1 + 1/(Ti*p) + Td*p/(1+Td*p/16 ))"))
        self.label_38.setText(_translate("MainWindow", "La saturation n\'est pas prise en compte si elle est mise à 0"))
        self.tabs.setTabText(self.tabs.indexOf(self.correcteurTab), _translate("MainWindow", "Correcteur"))
        self.menuFile.setTitle(_translate("MainWindow", "Fichier"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.menuAffichage.setTitle(_translate("MainWindow", "Affichage"))
        self.menuAide.setTitle(_translate("MainWindow", "Aide"))

# début code ajouté
    def launch(self, controleur):
            import sys
            app = QtWidgets.QApplication(sys.argv)
            MainWindow = QtWidgets.QMainWindow()
            ui = Ui_MainWindow(controleur)
            ui.setupUi(MainWindow)
            MainWindow.show()
            sys.exit(app.exec_())

    def actualisationAffichage(self, pos):
            self.poLabelValeurPosAct_c.setText(str(pos))
            self.poLabelValeurPosAct_col.setText(str(pos))
            self.poLabelValeurPosAct_p.setText(str(pos))
            self.poLabelValeurPosAct_v.setText(str(pos))
            self.Slider_col.setValue(pos * 10)

    def runpos(self):
        self.controleur.run()
        a=self.groupebuttoncor()
        print(a)
        print(self.controleur.parametres.getTdcour())


    def num(self, a):
            if (a == ''):
                return (0)
            else:
                return float(a)

    def getposfinechelonpos(self):
            return self.num(self.lineEditPosFEch_p.text())

    def getposfinrampepos(self):
            return self.num(self.lineEditPosFRam_p.text())

    def getcoefdirrampepos(self):
            return self.num(self.lineEditCoefDir_p.text())

    def getampcospos(self):
            return self.num(self.lineEditAmp_p.text())

    def getfreqcospos(self):
            return self.num(self.lineEditFreq_p.text())

    def getdurexppos(self):
            return self.num(self.lineEditDur_p.text())

    def getposfinechelonvit(self):
            return self.num(self.lineEditPosFEch_v.text())

    def getposfintrapvit(self):
            return self.num(self.lineEditPosFTri_v.text())

    def getplattrapvit(self):
            return self.num(self.lineEditPlat_v.text())

    def getcoefdirtrapvit(self):
            return self.num(self.lineEditCoefDir_v.text())

    def getampcosvit(self):
            return self.num(self.lineEditAmp_v.text())

    def getfreqcosvit(self):
            return self.num(self.lineEditFreq_v.text())

    def getdurexpvit(self):
            return self.num(self.lineEditDur_v.text())

    def getposfinecheloncour(self):
            return self.num(self.lineEditPosFEch_c.text())

    def getposfintrapcour(self):
            return self.num(self.lineEditPosFRam_c.text())

    def getplateautrapcour(self):
            return self.num(self.lineEditPlat_c.text())

    def getcoefdirtrapcour(self):
            return self.num(self.lineEditCoefDir_c.text())

    def getampcoscour(self):
            return self.num(self.lineEditAmp_c.text())

    def getfreqcoscour(self):
            return self.num(self.lineEditFreq_c.text())

    def getdurexpcour(self):
            return self.num(self.lineEditDur_c.text())

    def getKpos(self):
            return self.num(self.lineEditKPos_cor.text())

    def getTipos(self):
            return self.num(self.lineEditTiPos_cor.text())

    def getTdpos(self):
            return self.num(self.lineEditTdPos_cor.text())

    def getsatpos(self):
            return self.num(self.lineEditSatPos_cor.text())

    def getKvit(self):
            return self.num(self.lineEditKVit_cor.text())

    def getTivit(self):
            return self.num(self.lineEditTiVit_cor.text())

    def getTdvit(self):
            return self.num(self.lineEditTdVit_cor.text())

    def getTdvit(self):
            return self.num(self.lineEditSatVit_cor.text())

    def getKcour(self):
            return self.num(self.lineEditKCour_cor.text())

    def getTicour(self):
            return self.num(self.lineEditTiCour_cor.text())

    def getTdcour(self):
            return self.num(self.lineEditTdCour_cor.text())

    def getTdcour(self):
            return self.num(self.lineEditSatCour_cor.text())

    def getKcol(self):
        return self.num(self.lineEditK_col.text())

    def getTicol(self):
        return self.num(self.lineEditTi_col.text())

    def getTdcol(self):
        return self.num(self.lineEditTd_col.text())

    def groupebuttonpos(self):
            if self.radioButtonEch_p.isChecked() == True:  # rends 1 si le bouton d'echellon est coché dans la page position
                return 1
            if self.radioButtonRam_p.isChecked() == True:  # rends 2 si le bouton de rampe est coché dans la page position
                return 2
            if self.radioButtonSin_p.isChecked() == True:  # rends 3 si le bouton sinus est coché dans la page position
                return 3

    def groupebuttonvit(self):
            if self.radioButtonEch_v.isChecked() == True:  # rends 1 si le bouton d'echellon est coché dans la page vitesse
                return 1
            if self.radioButtonTri_v.isChecked() == True:  # rends 2 si le bouton de rampe est coché dans la page vitesse
                return 2
            if self.radioButtonSin_v.isChecked() == True:  # rends 3 si le bouton sinus est coché dans la page vitesse
                return 3

    def groupebuttoncour(self):
            if self.radioButtonEch_c.isChecked() == True:  # rends 1 si le bouton d'echellon est coché dans la page courant
                return 1
            if self.radioButtonRam_c_c.isChecked() == True:  # rends 2 si le bouton de rampe est coché dans la page courant
                return 2
            if self.radioButtonSin_c.isChecked() == True:  # rends 3 si le bouton sinus est coché dans la page courant
                return 3

    def groupebuttoncor(self):
            if self.radioButtonPos_cor.isChecked() == True:  # rends 1 si correction en posistion
                return 1
            if self.radioButton_13.isChecked() == True:  # rends 2 si correction en vitesse
                return 2
            if self.radioButtonCour_col.isChecked() == True:  # rends 3 si correction en courant
                return 3
            if self.radioButtonCas_col.isChecked() == True:  # rends 4 si correction en cascade
                return 4

    def runcolabo(self):
        print('merde')
        self.controleur.parametres.setCollaborativeRunning(True)
        self.controleur.teststop()

    def stopcolabo(self):
        self.controleur.parametres.setCollaborativeRunning(False)
# fin code ajouté

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

